run:
  timeout: "5m"
output:
  sort-results: true
  sort-order:
    - file
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - errname
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - mirror
    - nestif
    - nilerr
    - perfsprint
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
linters-settings:
  gocyclo:
    min-complexity: 10
  mnd:
    ignored-numbers:
      - "2"
      - "0600"
  gosec:
    config:
      G306: "0644"
issues:
  exclude-files:
    - (^|/)(gen|design)($|/)
    - _test\.go$
  include:
    # don't suppress missing exported method/function parameters
    - EXC0012
    # don't suppress missing package level comment
    #    - EXC0015
